services:
  app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./storage:/var/www/storage
      - ./public/uploads:/var/www/public/uploads
      - ./public/assets:/var/www/public/assets
      - ./app:/var/www/app
    environment:
      - BASE_PATH=
